site_name: Philipp Kopp
site_url: https://philipp-kopp.com
site_description: Philipp Kopp - sharing pragmatic knowledge about tech, making stuff and personal development
# repo_url: https://github.com/phil-m-kopp/phil-m-kopp.github.io
site_author: Philipp Kopp
copyright: >
  © 2023 <a href="https://www.linkedin.com/in/philipp-kopp-5b23a912a/">Philipp Kopp</a>. All rights reserved.
  | <a href="/privacy">👤 Privacy Policy / Datenschutz</a> | <a href="/imprint">📜Imprint / Impressum</a>
  | <a href="#__consent">🍪Cookie settings</a>

theme:
  language: en
  name: material
  custom_dir: overrides
  palette: 
    # Palette toggle for light mode
    - scheme: default
      media: "(prefers-color-scheme: light)"
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      media: "(prefers-color-scheme: dark)"
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  favicon: assets/favicons/favicon.ico
  logo: assets/favicons/android-chrome-192x192.png
  features:
    - header.autohide
    - navigation.footer
    # - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - navigation.tabs
    # - navigation.tabs.sticky
    # - navigation.sections
    - navigation.expand
    - navigation.indexes
    - navigation.top
    - toc.follow
    - search.suggest
    - search.highlight
    - search.share
    - announce.dismiss

  icon:
    tag:
      tech: fontawesome/solid/microchip
      html: fontawesome/brands/html5
      js: fontawesome/brands/js
      css:  fontawesome/brands/css3

extra_javascript:
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
  - assets/ext/tablesort.js

plugins:
  - search
  # - social
  - table-reader
  - macros
  - glightbox:
       auto_caption: false
  - redirects:
      redirect_maps:
        'index.md': 'articles/index.md'
  - blog:
      enabled: true
      blog_dir: articles/
      blog_toc: true
      post_date_format: medium
      post_url_format: "{slug}"
      post_excerpt: required
      post_excerpt_separator: <!--more-->
      archive: false
      categories_allowed:
        - Tech
      categories_toc: true
      pagination_per_page: 20
  - rss:
      enabled: true
      match_path: "blog.posts.*"
      comments_path: "#__comments"
      date_from_meta:
        as_creation: date
        as_update: date
        datetime_format: "%Y-%m-%d"
      categories:
        - categories
        - tags
  - tags:
      enabled: true
      tags_file: tags.md

nav:
  - "👦Phil": about.md
  - 📰All articles: 
    - articles/index.md
  # - 'A link': 'https://example.com/'
  - 📑Tags:
    - tags.md
  - 💻Tech: "/articles/category/tech/"

extra:
  tags:
    Tech: Tech
    HTML5: html
    JavaScript: js
    CSS: css
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/phil-m-kopp
      name: https://github.com/phil-m-kopp
    - icon: fontawesome/brands/linkedin 
      link: https://www.linkedin.com/in/philipp-kopp-5b23a912a/
      name: https://www.linkedin.com/in/philipp-kopp-5b23a912a/
    - icon: fontawesome/brands/discord
      link: https://discordapp.com/users/1160939065512833124
      name: https://discordapp.com/users/1160939065512833124
    - icon: fontawesome/brands/paypal
      link: https://paypal.me/PhilMKopp
      name: https://paypal.me/PhilMKopp
    - icon: material/email
      link: mailto:site@philipp-kopp.com
      name: site@philipp-kopp.com
    # - icon: material/newspaper-plus
    #   link: /feed_rss_created.xml
    #   name: "RSS: new posts"
    - icon: material/rss
      link: /feed_rss_updated.xml
      name: "RSS: all updates"

  analytics:
    provider: google
    property: G-HX3TQNQ246
    feedback:
      title: " "
      ratings:
        - icon: material/thumb-up-outline
          name: Good content
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/thumb-down-outline
          name: Bad content
          data: 0
          note: >- 
            Thanks for your feedback!<br><br>You can also use <a href="mailto:phil@philipp-kopp.com">phil@philipp-kopp.com</a> or the contact button 💬➡️ to send me a message
  consent:
    title: Cookie consent
    actions:
      - accept
      - manage
      - reject
    description: >- 
      I'd like to allow cookies/scripts to help improve the site content.
    cookies:
      analytics: Analytics -> what users like
      github: GitHub -> user commenting

markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - tables
  - footnotes
  - def_list
  - abbr
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.smartsymbols
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true